### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by anjishnu** [szagoruyko/loadcaffe#25]
Trying to run

$ luarocks install loadcaffe

[ 66%] Building CXX object CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: *** [CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o] Error 1
make[1]: *** [CMakeFiles/loadcaffe.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

Any ideas why this might be happening?

**Comment by anjishnu** [comment]
Fixed this by updating gcc and g++ versions from 4.6 to 4.9

**Comment by IdiosyncraticDragon** [comment]
@anjishnu I update my gcc and g++'s  version to 4.9.2, but found the error still occur：
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
Scanning dependencies of target loadcaffe
[ 66%] Building CXX object CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o
cc1plus: error: unrecognized command line option '-std=c++11'
make[2]: *** [CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o] Error 1
make[1]: *** [CMakeFiles/loadcaffe.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝gcc and g++ version======
root@51b51dd968fd:~# g++ --version
g++ (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@51b51dd968fd:~# gcc --version
gcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
